### PR TITLE
Adding the ability to specify the visibility when retrieving a template

### PR DESCRIPTION
**Pull request by FJBDev**
As my Visual Studio rearranged the indentation and other "beautifcation" features, see my change on line 948 to 959

### CODE REVIEW

**Comment by FJBDev** [comment]
Please accept this pull request as it will allow the .NET SDK users to use the shared templates feature.

**Comment by FJBDev** [comment]
Hi, anybody here ?

**Comment by FJBDev** [comment]
@SeungChoi @ehardy @lhsieh814 . Calling out to the main commiters to see if someone can look at my Pull Request ?

**Comment by SeungChoi** [comment]
Added the ability to specify the visibility when retrieving a template

**Pull request closed without merging**
